source 'https://rubygems.org'

gem 'rails',                '4.2.0'
gem 'bcrypt',               '~> 3.1.9'
gem 'faker',                '1.4.2'
gem 'will_paginate',           '3.0.7'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'sass-rails',           '5.0.1'
# gem 'bootstrap-sass',       '3.2.0.0' # denna bör laddas via bower
gem 'uglifier',             '2.5.3'
gem 'coffee-rails',         '4.1.0'
gem 'jquery-rails',         '4.0.3' # denna bör också laddas via bower
gem 'turbolinks',           '2.3.0'
gem 'jbuilder',             '2.2.3'

gem 'sdoc',                 '0.4.0', group: :doc

#Api gems
gem 'active_model_serializers'
gem 'responders',           '~> 2.0'
gem 'jwt'
gem 'geocoder'

#SPA gems
gem 'bower-rails'
gem 'angular-rails-templates'

# SPA CORS
gem 'rack-cors', :require => 'rack/cors'
# SPA css
gem 'neat'

group :development, :test do
  gem 'sqlite3',     '1.3.10'
  gem 'byebug',      '3.4.0'
  # gem 'web-console', '2.0.0.beta3' #Funkar ej i windows
  gem 'spring',      '1.1.3'
  # SPA gems
  gem "rspec-rails", "~> 2.0"
  # test https://github.com/modeset/teaspoon
  gem 'teaspoon'
  # http://phantomjs.org/
  gem 'phantomjs'
  # browser tests
  gem "capybara"
  gem "selenium-webdriver"
  #
  gem "database_cleaner"
end

group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
end

group :production do
	#https://github.com/Crowdtilt/CrowdtiltOpen/issues/168
	#Verkar saknas stöd för dessa i windows
  #gem 'pg',             '0.17.1'
  #gem 'rails_12factor', '0.0.2'
  #gem 'unicorn',        '4.8.3'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
